name: 'generate latex pdf'
description: 'generate latex pdf'
inputs:
  path-to-tex-file:
    description: 'Who to greet'
    required: true
    default: 'World'
  output-directory:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: docker run --name latex-container -dit -v $(pwd):/source jakerl/latex
      shell: bash
    - id: random-number-generator
      run: docker exec latex-container pdflatex -output-directory source/${{ inputs.output-directory }} source/${{ inputs.path-to-tex-file }}
      shell: bash
