name: 'generate latex pdf'
description: 'generate latex pdf'
inputs:
  path-to-tex-file:
    description: 'path to the tex file you want to generate pdf from'
    required: true
    default: 'file.tex'
  output-directory:
    description: 'path to the directory you want the generated pdf to be placed'
    required: true
    default: 'output'
runs:
  using: "composite"
  steps:
    - run: docker run --name latex-container -dit -v $(pwd):/source jakerl/latex
      shell: bash
    - run: docker exec latex-container pdflatex -output-directory source/${{ inputs.output-directory }} source/${{ inputs.path-to-tex-file }}
      shell: bash
