name: 'publish resume'

on:
  push:
    branches:
      - 'main'

jobs:
  run_docker_container:
    runs-on: ubuntu-latest
    steps:
    - name: checkout this repository
      uses: actions/checkout@v2
    - name: checkout website repository
      uses: actions/checkout@v2
      with:
        repository: jakerl/jakerl.github.io
        path: website
        token: ${{ secrets.access_token }}
    - name: generate normal resume
      uses: jakerl/generate-latex-action@v0.0.7
      with:
        path-to-tex-file: resume.tex
        output-directory: .
    - name: generate normal resume
      uses: jakerl/generate-latex-action@v0.0.7
      with:
        path-to-tex-file: resume.tex
        output-directory: .
        extra-arguments: --for-print
    - name: move produced resume to website directory
      run: mv resume.pdf website/resume.pdf
    - name: deploy resume to website
      run: |
        git -C website config user.email ${{ secrets.email }}
        git -C website config user.name $GITHUB_ACTOR
        git -C website add resume.pdf
        git -C website commit -m "updating resume"
        git -C website push
