name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: checkout resume repository
        uses: actions/checkout@v2
        with:
          path: resume
      - name: compile resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume/resume.tex
      - name: checkout website repository
        uses: actions/checkout@v2
        with:
          repository: jakerl/jakerl.github.io
          path: website
          token: ${{ secrets.access_token }}
      - name: move resume
        run: mv resume.pdf website/resume.pdf
      - name: commit
        run: |
          git -C website config user.email ${{ secrets.email }}
          git -C website config user.name $GITHUB_ACTOR
          git -C website add resume.pdf
          git -C website commit -m "updating resume"
          git -C website push
