name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: checkout resume repository
        uses: actions/checkout@v2
        with:
          path: resume
      - name: compile resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume/resume.tex
      - name: checkout website repository
        uses: actions/checkout@v2
        repository: jakerl/jakerl.github.io
        with:
          path: website
      - name: move resume
        run: mv resume.pdf resume/resume.pdf
      - name: commit
        run: |
          git -C resume config user.email jakerobinsonlieberman@gmail.com
          git -C resume config user.name $GITHUB_ACTOR
          git -C resume add resume.pdf
          git -C resume commit -m "updating resume"
          git -C resume push
