name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: checkout resume repository
        uses: actions/checkout@v2
        with:
          path: resume
      - name: compile resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume/resume.tex
      - name: checkout website repository
        uses: actions/checkout@v2
        with:
          path: website
      - name: move resume
        run: mv resume.pdf resume/resume.pdf
      - name: commit
        run: |
          git commit -m "updating resume"
          git push
