name: Build LaTeX document
on: [push]
jobs:
  run_docker_container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run container
      run: docker build -t latex-image .
