name: 'preview resume'

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  run_docker_container:
    runs-on: ubuntu-latest
    steps:
    - name: checkout this repository
      uses: actions/checkout@v2
    - name: generate printable resume
      uses: jakerl/generate-latex-action@v0.0.7.1
      with:
        path-to-tex-file: resume.tex
        output-directory: .
        extra-arguments: --for-print
    - name: upload resume as artifact
      uses: actions/upload-artifact@v2
      with:
        name: resume
        path: resume.pdf
